[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://helio-backend.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200