services:
  - type: web
    name: helio-telemedicine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_combined:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: helio-production-secret-2025
      - key: JWT_SECRET_KEY
        value: helio-jwt-production-2025
      - key: PORT
        value: "10000"