@echo off
cd /d "%~dp0"
echo 🏥 Starting Helio Healthcare Backend...
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo Installing/updating dependencies...
pip install flask flask-cors flask-jwt-extended bcrypt --quiet
echo Starting backend server...
python backend\app_simple_login.py
pause