# Nixpacks configuration for backend
[phases.setup]
providers = ["python"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python -c 'print(\"Backend build complete\")'"

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --workers 3 --timeout 300"